### PR TITLE
Automatically close keyboard in gym mode

### PR DESCRIPTION
**Pull request by KhushbuBora**
#52 
Added focusNode propert in gymMode to close keyboard when pressed on save button.

### CODE REVIEW

**Review by M123-dev — APPROVED** [review]
The changes look good thanks.

-----------

Only one thing the line length is set 100 but the IDE's do not know that and format to the standard length. You can reformat by running: 
flutter format --line-length=100 .


@rolandgeider why is the line limit set to 100, I think it adds more effort than it brings code clarity

**Comment by KhushbuBora** [comment]
> The changes look good thanks.
> 
> Only one thing the line length is set 100 but the IDE's do not know that and format to the standard length. You can reformat by running:
> flutter format --line-length=100 .
> 
> @rolandgeider why is the line limit set to 100, I think it adds more effort than it brings code clarity

Sure

**Comment by rolandgeider** [comment]
I find 100 characters a good compromise, 80 seems too narrow to me. But we should mention this somewhere in the README or similar

**Comment by rolandgeider** [comment]
I'm reading on the [flutter docs](https://flutter.dev/docs/cookbook/forms/focus) that the focus node should be created in initState and later disposed. Can you add these changes? Then this can be merged

**Comment by KhushbuBora** [comment]
Okay..

**Pull request merged**
