### PR TITLE
Start Time Validator

### PR DESCRIPTION
**Pull request by arun-muralidharan**
Implemented start time validator to ensure start time is not ahead of end time in gym mode.

Also, fixed a bug where editing the end time changed the start time text.

### CODE REVIEW

**Comment by arun-muralidharan** [comment]
Fix for [Issue#35](https://github.com/wger-project/flutter/issues/35)

**Comment by rolandgeider** [comment]
Looks good, I'll test this later.

Can you add yourself to AUTHORS.md?

**Comment by arun-muralidharan** [comment]
Will do, thanks!

**Comment by rolandgeider** [comment]
The only thing I would perhaps change is adding a `errorMaxLines: 2` to the InputDecoration of the TextFormField where the new validator is, then the error message can be shown entirely.

And while this is not complex logic, I would suggest adding a simple test. I know writing tests is tedious and not fun, but I can't tell you how often they saved my ass while developing for wger. The good thing is that because the logic is simple, so are the tests! Something like this would have us covered:

```dart
void main() {
  test('Test the TimeOfDayExtension', () {
    final time1 = TimeOfDay(hour: 20, minute: 00);
    final time2 = TimeOfDay(hour: 10, minute: 00);
    final time3 = TimeOfDay(hour: 20, minute: 00);

    expect(time1.isAfter(time2), true);
    expect(time1.isBefore(time2), false);
    expect(time2.isAfter(time1), false);
    expect(time2.isBefore(time1), true);

    expect(time1.isAfter(time3), false);
    expect(time1.isBefore(time3), false);
  });
}
```

**Comment by arun-muralidharan** [comment]
You are right. I'll make the edits. :)

**Comment by arun-muralidharan** [comment]
I added the `errorMaxLines` and created a test file for extensions.

**Comment by rolandgeider** [comment]
Great, thanks!!

**Pull request merged**
