### PR TITLE
Add icons, merge email and its verify fields

### LINKED ISSUE #381: Feature Request related to improving User Profile Page UI
## Use case
- Currently, the User Profile page does't look that much good due to the UI. The text/fields should be shown on the top instead of bottom to make it look a bit better.
- We can also make the List Tile view widgets more attractive by simply adding some icons in the front and few more things.

## Proposal
- Top align the fields in User Profile Page.
- Improve the UI by adding leading icons. Will try to add screenshots in the comments.
- Maybe we can add border if it looks good.
- Any other idea or suggestions are welcome and would be appreciated.

Below if the screenshot after simply moving it to the top - 

I would like to work on this if possible **please assign this request to me**.
Thanks

### PR DESCRIPTION
**Pull request by tejasbirsingh**
Fixes #381 

**Testing -** 
- flutter test successful
- Screenshot when email is not verified -

- Screenshot when email is verified -

### CODE REVIEW

**Comment by tejasbirsingh** [comment]
All tests are passing on my local machine - 

01:10 +177 ~2: All tests passed!
Tejas Bir Singh  wger-flutter  ➜ ( user-profile-UI-changes  2)  ♥ 23:21 

**Comment by rolandgeider** [comment]
oh yes, that one is sometimes a bit flaky since we check for the time it was run, don't worry

**Comment by tejasbirsingh** [comment]
Hey, any update or questions on PR ? 

Thanks

**Comment by rolandgeider** [comment]
no, everything looks fine, I was just a bit busy. Will merge this as soon as I can

**Pull request merged**
