### PR TITLE
Fix for #42/ Automatic linting

### PR DESCRIPTION
**Pull request by M123-dev**
```line 1: syntax error near unexpected token `( ```

### CODE REVIEW

**Comment by M123-dev** [comment]
First run finished: https://github.com/wger-project/flutter/commit/7492b53c67597e21790487a83b50b3ccaba8b97f

**Comment by rolandgeider** [comment]
I saw it! Having stuff like this automated is such a good feeling

**Comment by rolandgeider** [comment]
Mhh, it seems it throws an error If there are no linting changes to commit

https://github.com/wger-project/flutter/runs/2869078524

**Comment by M123-dev** [comment]
Thats not good, I just checked, doesnt look like github actions support any kind of allow-failure
https://github.com/actions/toolkit/issues/399, maybe we can check if anything has changed before running the commit step

**Comment by rolandgeider** [comment]
Yes, perhaps it's possible to add some simple if checks in the job definition?

**Comment by M123-dev** [comment]
Lets hope that https://github.com/wger-project/flutter/pull/47 fixes this problem

**Pull request merged**
