### PR TITLE
Fix for RiR slider

### PR DESCRIPTION
**Pull request by TaarnStar**
# Proposed Changes

- When trying to move the slide on slider in RiR, there were initialization errors (#103)

The RiR slider value was a final variable so it couldn't be reassigned and reinitialized the value. I changed to use the final variable only on first initialization, for the rest of the slider using I made a temp variable that isn't final so everything works as it supposed to..

## Please check that the PR fulfills these requirements

- [ ] Set a 100 character limit in your editor/IDE to avoid white space diffs in the PR
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added yourself to AUTHORS.md

### CODE REVIEW

**Comment by rolandgeider** [comment]
You are right. I think I'll leave the warning for now, then we don't forget about this

**Comment by TaarnStar** [comment]
I removed the new mutable variable and removed the final keyword for those two properties, the slider works fine now, only the warning is there of using a final keyword on an @immutable class

**Comment by M123-dev** [comment]
Sorry @rolandgeider this error is probably on me😅

**Comment by rolandgeider** [comment]
Don't worry, I also didn't notice. We should probably handle the objects differently and more cleanly

**Pull request merged**
