### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by hn-n**
## Description (Proposed Changes)

- Added server information automatically on the debug mode
- Reset when switching to Registration

## Link to the issue : 
https://github.com/wger-project/flutter/issues/454

## Checklist

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Added yourself to AUTHORS.md

### CODE REVIEW

**Comment by rolandgeider** [comment]
can you also add the test server there? so something like DEFAULT_SERVER_TEST (and it's probably a good idea to rename the DEFAULT_SERVER to DEFAULT_SERVER_PROD)

**Comment by hn-n** [comment]
okay ✅ , added the two servers @rolandgeider

**Comment by rolandgeider** [comment]
did you forget to push? :D

**Comment by hn-n** [comment]
done @rolandgeider

**Pull request merged**
