### PR TITLE
Add MasonryGridView to the Gallery

### PR DESCRIPTION
**Pull request by Aaliya-Ali**
# Proposed Changes

- Replaced the GridView with a MasonryGridView in the Gallery Screen

## Please check that the PR fulfills these requirements

- [ ] Set a 100 character limit in your editor/IDE to avoid white space diffs in the PR
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added yourself to AUTHORS.md

### CODE REVIEW

**Review by rolandgeider — APPROVED** [review]

**Comment by rolandgeider** [comment]
FYI, I have approved the PR so that it will count towards hacktoberfest

**Comment by rolandgeider** [comment]
You already did contribute :)

Basically what we could still figure out are the tests. It also shouldn't be that we invest three times as much fixing this than in implementing the feature so if we can't come up with any ideas, we can just mark the test as skipped and open an issue so this doesn't get lost

**Comment by Aaliya-Ali** [comment]
Makes sense. Thanks again :)

**Comment by rolandgeider** [comment]
All green now, thanks!

**Pull request merged**
