### PR TITLE
Maintenance PR

### PR DESCRIPTION
**Pull request by 12people**
Various minor fixes, partly to get the project to build on macOS with the latest version of Flutter, partly to fix lint warnings.

All changes are annotated in the relevant commits.

### CODE REVIEW

**Comment by 12people** [comment]
The CI tests all fail because they use an old Dart version.
Could the Dart SDK for those checks be updated?

**Comment by 12people** [comment]
I also added new icons for all platforms.
iOS now has sharper (but optimized via optipng) icons, macOS now has squircle icons, as is the norm on latest macOS versions, and Android now has a vector-based icon, which also serves as a monochrome icon (solving the problem that is mentioned in #442 ).

**Comment by rolandgeider** [comment]
Cool, thanks!

Yeah, we need to finish work on `fix/replace-chart-lib`, the old chart lib was discontinued and is preventing us from updating flutter to something not old, but it's just some polishing left (#433)

**Comment by rolandgeider** [comment]
> and Android now has a vector-based icon, which also serves as a monochrome icon (solving the problem that is mentioned in #442 ).

aweome, will check it out

**Comment by 12people** [comment]
> Cool, thanks!
> 
> Yeah, we need to finish work on `fix/replace-chart-lib`, the old chart lib was discontinued and is preventing us from updating flutter to something not old, but it's just some polishing left (#433)

Oh, what I did was just replace it with the community-maintained fork: [`community_charts_flutter`](https://pub.dev/packages/community_charts_flutter). It's basically a drop-in replacement.

I do agree, though, that using `fl_charts` is probably best in the long run.

**Comment by 12people** [comment]
@rolandgeider Manually.

I made a template for app icons in Figma for myself, which I've used for all my projects and it was easy to just [plug the wger icon into that](https://www.figma.com/file/5APvN3X7Lb1LQkechUPNbg/wger-design?type=design&node-id=1506%3A9793&mode=design&t=5EC7aojTMtPKNQlW-1) too.

Figma lets you specify multiple export sizes as well as suffixes, so once you've got that set up in Figma, getting the iOS and macOS icons is just a simple matter of dragging those exports into the right folder. For Android, I exported an SVG for the foreground and converted that into an Android Drawable via Android Studio.

(I didn't update any of the old Android PNGs, as that would require manually renaming each exported PNG and dragging it into the right folder — while Figma supports specifying export prefixes and suffixes, it does not support specifying different folders for each export, so it's not quite as simple to generate PNG icons for Android. I suppose you could write an automated script for this, but a vector version works well enough for everything v26 and onward, so I didn't see a need to.)

**Comment by rolandgeider** [comment]
so if/when we change the target sdk to 26 we could remove the android png icons, right?

**Comment by 12people** [comment]
> so if/when we change the target sdk to 26 we could remove the android png icons, right?

Sure.

That said, the vector drawable in the PR is used automatically here for all platforms 26 and above, so the PNGs only serve as fallback for older platforms.

**Comment by rolandgeider** [comment]
👍🏻 

yeah, that's what I meant. I think at the moment we have something lower than that, like 23 or so

**Comment by rolandgeider** [comment]
Merged thanks :)

**Pull request merged**
