### PR TITLE
Bad internet duplicate exercise entries #54

### PR DESCRIPTION
**Pull request by ThilinaTCH**
# Proposed Changes

- Add loading indicator and disable save button on saving 

Related Issues (if applicable)

- NA

## Please check that the PR fulfills these requirements

- [x] Set a 100 character limit in your editor/IDE to avoid white space diffs in the PR
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Added yourself to AUTHORS.rst

### CODE REVIEW

**Comment by ThilinaTCH** [comment]
@rolandgeider All tests are passing locally. Also the tests failed here seems not relevant the the changed I did

**Comment by M123-dev** [comment]
Thanks a lot @ThilinaTCH besides my comment everything looks good

**Comment by ThilinaTCH** [comment]
> Thanks a lot @ThilinaTCH besides my comment everything looks good

Addressed this comment 👍

**Comment by rolandgeider** [comment]
> @rolandgeider All tests are passing locally. Also the tests failed here seems not relevant the the changed I did

There are a couple (as in just 2) that sometimes fail, mostly on github. One of these days I'll sit down and take a look

**Comment by ThilinaTCH** [comment]
> > @rolandgeider All tests are passing locally. Also the tests failed here seems not relevant the the changed I did
> 
> There are a couple (as in just 2) that sometimes fail, mostly on github. One of these days I'll sit down and take a look

Yeah seems they are passing now ✅

**Comment by rolandgeider** [comment]
Looks great, thanks!

**Pull request merged**
