### PR TITLE
Improve flatpak local build

### PR DESCRIPTION
**Pull request by bbkz**
## Description (Proposed Changes)

For `flatpak_packager.dart` `localReleaseAssets` in  `flatpak_meta.json`  needs to be empty (kind of). But for `manifest_generator.dart` it needs to be filled correctly otherwise the flatpak manifest will not be correct.

So i handled the data in a seperate json file.

## Checklist

Please check that the PR fulfills all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] Set a 100 character limit in your editor/IDE to avoid white space diffs in the PR
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Added yourself to AUTHORS.md <- not in application code
- [x] Updated/added relevant documentation (doc comments with `///`).
- [ ] Added relevant reviewers.

### CODE REVIEW

**Comment by rolandgeider** [comment]
@12people this is your flatpak script, perhaps something you can use?

**Comment by 12people** [comment]
@bbkz @rolandgeider 

Actually, I think the point of the `localReleaseAssets` aspect of the json file was misunderstood.
It's there to define local release assets, which is useful even when building a local Flatpak (out of local files, e.g. for testing).

Whether to use the local assets or to download them from Github instead is defined using the `--github` flag for the script.

The reason why there's one manifest file instead of two is to have one place for specifying all the necessary data instead of two (which could lead to inconsistencies).

**Comment by 12people** [comment]
BTW, I've since updated the package files somewhat, for my own project: https://gitlab.com/enjoyingfoss/parlera/-/tree/master/flatpak/scripts?ref_type=heads

Will submit a pull request later when I get to it.

**Comment by bbkz** [comment]
Nice, thank you. Yes, i wanted to build the local flatpak package and added this, for not having to manually add the assets after building the package.

For the local flatpak installation with `flatpak-builder --user --install flatpak-build-dir de.wger.flutter.json`, i had to add this.

Happy to see your latest impelmentation ;-)

**Comment by rolandgeider** [comment]
might also be a good idea to separate the scripts into their own repo (I think we already talked about this once?) and, for the moment, just copy it from there. At least that way we will know if there are any upstream changes

**Pull request closed without merging**
