### PR TITLE
Modified Authentication Part as per issue #101

### PR DESCRIPTION
**Pull request by AmanNegi**
# Proposed Changes

- Added a check during Login and Signup to ensure the user is using a valid app version. If the user login is successful but the app version is not supported the user is now directed to the Update App page.

- The Error dialog displayed was showing the error in an uneasy fashion, I modified the error dialog as well. Changes I made in Error Dialog are:
  > - Made the Errors alignment to `CrossAxisAlignment.start`.
  > - The `key` property of the error was coming all lowercase, I added a few lines of code to ensure the first letter was capitalized to ensure the error was more formal and readable.

- Now the user login process is much more streamlined with the loading indicator, error handling dialog and app version validator.

Related Issues (if applicable)
This PR is regarding issue #101 
-

## Please check that the PR fulfills these requirements

- [✔] Set a 100 character limit in your editor/IDE to avoid white space diffs in the PR
- [✔ ] Tests for the changes have been added (for bug fixes / features)
- [ ✔] Added yourself to AUTHORS.md

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks for the PR, I'll try to test it as soon as I can

**Comment by AmanNegi** [comment]
Great! 🍀😊

Can I help you with the testing? Like providing you APK or recording the authentication process.

**Comment by rolandgeider** [comment]
thanks, but I'll manage, just need to find a quiet evening :)

**Comment by AmanNegi** [comment]
Okay great, let me know :)

**Comment by rolandgeider** [comment]
Yes, this is indeed an improvement, thanks!

**Comment by AmanNegi** [comment]
Great! 🤗
Will this PR be merged?

**Comment by rolandgeider** [comment]
merged, thanks! 🥳

**Pull request merged**
